// student Side
//get the list of student
export const GET_STUDENT_LIST_PROGRESS = "GET_STUDENT_LIST_PROGRESS"
export const GET_STUDENT_LIST_SUCCESS = "GET_STUDENT_LIST_SUCCESS"
export const GET_STUDENT_LIST_ERROR = "GET_STUDENT_LIST_ERROR"

//Add or post student
export const POST_STUDENT_PROGRESS = "POST_STUDENT_PROGRESS"
export const POST_STUDENT_SUCCESS = "POST_STUDENT_SUCCESS"
export const POST_STUDENT_ERROR = "POST_STUDENT_ERROR"

//delete the student
export const DELETE_STUDENT_PROGRESS = "DELETE_STUDENT_PROGRESS"
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR"

//update the student
export const UPDATE_STUDENT_PROGRESS = "UPDATE_STUDENT_PROGRESS"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR"