// subadmin Side
//get the list of subadmin
export const GET_SUBMIN_LIST_PROGRESS = "GET_SUBMIN_LIST_PROGRESS"
export const GET_SUBMIN_LIST_SUCCESS = "GET_SUBMIN_LIST_SUCCESS"
export const GET_SUBMIN_LIST_ERROR = "GET_SUBMIN_LIST_ERROR"

//Add or post subadmin
export const POST_SUBMIN_PROGRESS = "POST_SUBMIN_PROGRESS"
export const POST_SUBMIN_SUCCESS = "POST_SUBMIN_SUCCESS"
export const POST_SUBMIN_ERROR = "POST_SUBMIN_ERROR"

//delete the subadmin
export const DELETE_SUBMIN_PROGRESS = "DELETE_SUBMIN_PROGRESS"
export const DELETE_SUBMIN_SUCCESS = "DELETE_SUBMIN_SUCCESS"
export const DELETE_SUBMIN_ERROR = "DELETE_SUBMIN_ERROR"

//update the subadmin
export const UPDATE_SUBMIN_PROGRESS = "UPDATE_SUBMIN_PROGRESS"
export const UPDATE_SUBMIN_SUCCESS = "UPDATE_SUBMIN_SUCCESS"
export const UPDATE_SUBMIN_ERROR = "UPDATE_SUBMIN_ERROR"